[build]
  publish = "public"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "12"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
